### ISSUE TITLE
Some questions about source code binarize

### ISSUE THREAD

**Issue by hiyashi-CianDuo** [sliedes/binarize#1]
Hello,
What kind of neural network was used to train the model used in this source code?
Are there any references? Thank you.

**Comment by sliedes** [comment]
Hi,

The code defining the model and doing the training is in [seg/binarization.ipynb](https://github.com/sliedes/binarize/blob/master/seg/binarization.ipynb); look under the subtitle _Model definition_. There's also diagrams of the model architecture there.

It's largely adapted from the [TensorFlow image segmentation tutorial](https://www.tensorflow.org/tutorials/images/segmentation), and the code is probably easier to understand if you go through that tutorial first; it has more verbose explanations than my code.

Basically, the model is a modified U-net, where the encoder is a MobileNet v2 (which is not trained); the outputs of some of its layers at specific scales are used in different parts of the decoder (just as in the image segmentation tutorial).

Differences to the image segmentation tutorial that I can think of:

- The segmentation tutorial trains a multiclass classifier for three classes (pixel belonging to the object, border pixel, neither). My code instead trains a binary classifier (ink/no ink).
- The output from the resulting binary classifier is further used to train an isotonic regression to convert the classifier's output to a probability. This way we get for each pixel a probability of it being ink.
- The probability from the previous step is used directly as the value of the output pixel, ie. 50% probability of being ink results in 50% gray.

I haven't published anything on this... Maybe I should write a blog post or something. I'm no academician, so I skipped that part :)

Hope this helps. Feel free to ask more questions if you don't understand something!
